### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by trebmuh** [ibancg/lingot#11]
Hi all.

I've noticed a bit of activity here on the last weeks. Is any new version on the way?

Best.

**Comment by ibancg** [comment]
Hi!. Yes, we got a little push with some nice code contributions, so we are aiming to release the long-awaited version 1.0 in the following days, just a bit more testing and we should be there.

**Comment by trebmuh** [comment]
Nice to read. Congratz guys.

**Comment by ibancg** [comment]
Lingot 1.0.0 finally released!, check it out.
We close this thread.
