### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by ibancg** [ibancg/lingot#12]
In order to avoid problems like the fixed in commit c12e59b1ec8fea3838b3b0354a91d6f6293492ed, we need to integrate CI with at least:

* Builds with all the possible switches on and off.
* Running unit tests.

**Comment by jairochapela** [comment]
The "problems like this" link is broken. 🙁
Anyway, a CI tool is welcome, for testing automation purposes at least.

**Comment by ibancg** [comment]
Link fixed.

**Comment by ibancg** [comment]
Implemented in pull request #16. 

Other platforms / compilers / options are pending.
