### ISSUE TITLE
Needle display spread

### ISSUE THREAD

**Issue by ibancg** [ibancg/lingot#28]
Original from @wolftune:
`
@ibancg realized there's an issue with the display and the spread is +/- 50. Makes it pretty much unusable. Is there a way to update this?
`
![image](https://user-images.githubusercontent.com/26056586/69924328-b3d8cd00-145f-11ea-9c09-313dfc0c6278.png)

**Comment by ibancg** [comment]
@wolftune Do you mean the spread is too big? It adapts to the separation between consecutive notes.

I find it quite usable, but if this is a big issue, we could make it fixed / configurable.

**Comment by wolftune** [comment]
@ibancg what @alignwaivers was saying in https://github.com/ibancg/lingot/issues/26#issuecomment-560188827 is that there was a deprecation. The goal is exactly as you describe: adapting to the separation between consecutive notes. When @alignwaivers built the version with the scale-name support, he found that this behavior was not working. It was sticking to 100¢ range in the display even when loading a scala file with smaller intervals between notes.

**Comment by ibancg** [comment]
Ah sorry @wolftune I mislabeled you.

To be precise: **the range for the needle adapts to the worst case**, i.e., the maximum gap between two consecutive notes. Such behavior is still working for me.

I guess it will be better using the minimum gap. I'll try that on a new branch and see if someone can give feedback.

**Comment by wolftune** [comment]
That's okay, I've been working with @alignwaivers so I know what's up, although he was the one who built and tested. Although I think you are right that the minimum gap is the way to go, that shouldn't have been the issue because we were testing with 41-EDO, i.e. the *same* gap for all pitches.

Perhaps the minimum adjustment will fix this anyway.

**Comment by ibancg** [comment]
I see, I just tested the 41-EDO, with the current implementation (maximum gap), and it adapts to something better than -50/+50 cent:

![image](https://user-images.githubusercontent.com/5263631/71548658-b9b7c480-29b1-11ea-9749-44b8e9d72aa2.png)

I am using the `master` branch after merging pull request #29. If you don't get the same behavior there could be a bug somewhere.

**Comment by alignwaivers** [comment]
Just fyi this does work correctly now, I tried it again. Thanks, it works fantastic, awesome.

Still not sure why the default base value is assumed to be middle C though, is there a reason for this?

**Comment by ibancg** [comment]
Ok @alignwaivers, thanks for the feedback!, I'll continue discussing the other issue in #25.
