### ISSUE TITLE
feature request: vertical bar on spectrum at target tone

### ISSUE THREAD

**Issue by tpapp** [ibancg/lingot#38]
The deviation needle wobbles a bit when the tone is identified from the spectrum.

I understand that this is to be expected, but it would be nice to overlay a vertical bar at the target frequency on the *spectrum*. This would help the user pick up the deviation visually in a more stable way for micro-tuning. I attach an illustration of the suggestion, where the E2 bar would be at 82.407 Hz (drawn here with blue), which would be especially visible when the window is fullscreen.

![lingot](https://user-images.githubusercontent.com/84122/74589483-0e68da80-5006-11ea-98be-cc05c874be9b.png)

**Comment by ibancg** [comment]
Yes that looks easy, I can give it a try.

I think it will make more sense if the spectrum is displayed in logarithmic scale on the frequency axis, so the same error in _cents_ will be the same distance in pixels, regardless of the absolute frequency. 

I will play around with both scaling options.

**Comment by ibancg** [comment]
This has been added to `master` branch. It does not add a lot yet in my opinion, as the blue line is never too far away from the red one, but maybe in the future it is useful with zoom or log scale.

![image](https://user-images.githubusercontent.com/5263631/80865423-b434f880-8c89-11ea-8296-de81879a7a46.png)
