### ISSUE TITLE
feature request: dampening the deviation

### ISSUE THREAD

**Issue by tpapp** [ibancg/lingot#39]
Either for the gauge needle or the strobe in #31, some of the fluctuation picked up is inherently noise/measurement error.

It would be great to introduce some dampening, so that the position of eg needle is
```
alpha * old_position + (1 - alpha) * lingot_filter_filter_sample(...)
```
with some `alpha` close to `0`, eg calculated from a half-life parameter (the user can customize) and the updating frequency.

**Comment by ibancg** [comment]
Yes, there is an IIR filter on the gauge to give some feeling of "inertia". I like the current response, but I don't want to ruin the tuning capabilities, so I am in favor of bringing some parameter to the GUI.

[There are already parameters](https://github.com/ibancg/lingot/blob/cc1cf92cde299d906f10616b25868e4fd3cf6d8f/src/lingot-gauge.c#L62) for tweaking the responsiveness and damping of the filter, I will try those ones, or the extra parameter you propose (which can be "embedded" in the IIR filter as an extra pole).

**Comment by ibancg** [comment]
I updated the filter parameters on `master` branch to make the needle quicker and more damped.

It would be good to know if this works better for you @tpapp.

**Comment by tpapp** [comment]
It is an improvement. Can you please make this parameter tunable in the settings?

I also found that using a large FFT size and a 2s temporal buffer improves the issue.

**Comment by ibancg** [comment]
I raised the default values a bit more, and externalized some UI settings to a file in `~/.config/lingot/ui-settings.json`, created by LINGOT after the first use.

In that file you can change (with LINGOT not running) the values for `gaugeAdaptationConstant` and `gaugeDampingConstant`. They will be read the next time you launch the application.

At the moment I cannot make those parameters available via GUI.

**Comment by ibancg** [comment]
This was done (up to the point explained above) in Lingot 1.1.0, just released.
