### ISSUE TITLE
Apply last patches by Nicolas Boulenguez

### ISSUE THREAD

**Issue by ibancg** [ibancg/lingot#5]
Nicolas sends us the [patches attached](https://github.com/ibancg/lingot/files/2087742/suggestions-on-ffcf2af5.zip), intended to by applied from ffcf2af5e540336641626a3dec75eaeef62409b9

The problem is that the format is not recognized by `git am` nor `git apply`, probably due to the `dos2unix` operations starting in patch 06/12.

I tried with a test git repository, and I cannot import a patch generated with `git format-patch` that involves a `dos2unix` operation.

**Comment by ibancg** [comment]
It is worth mentioning that the patch can be applied to the working copy with `patch -p1`

**Comment by ibancg** [comment]
@jairochapela Any ideas?

**Comment by ibancg** [comment]
I can split the patches and apply 01/12 to 05/12, but I cannot apply 06/12 no matter what.

**Comment by jairochapela** [comment]
Ok, that's done.
After converting CRLF to LF into the patch file, the applying operation was successful.
Changes committed.

**Comment by ibancg** [comment]
We will have to roll back, the changes were applied directly to master and introduce/awake SIGSEGV (at least one).
I will apply the changes in a separate branch, and then merge, as I did with the previous changes.
BTW , we should respect the individual commits by Nicolas, and then patch on top.

**Comment by ibancg** [comment]
Ok, I created the branch `patches-nicolas-02`, we should not merge until we fix the SIGSEGV (opening issue now)

**Comment by ibancg** [comment]
Commit 49a80112fb27f9ab20b57ebad3fab8927856c548 should fix the SIGSEGV.
